### ISSUE TITLE
integration: calculate required decimal precision in printed output from parameters

### ISSUE THREAD

**Issue by klaeufer** [LoyolaChicagoCode/unoapi-dpcpp-examples#5]
ceil(log10(1 / dx))

**Comment by gkthiruvathukal** [comment]
@klaeufer 
Although I agree with this thinking, I think in this context you are talking about the printed result. So can there be an option to indicate either: (a) the format string for the result (for use with fmt::) or (b) --precision N (places after decimal point).  This gives users the most control. 

Of course, your formula can amount to a sensible default in the spirit of convention over configuration.
