### ISSUE TITLE
third version of integration: using sycl::buffer in a non-parallel/host-only context

### ISSUE THREAD

**Issue by klaeufer** [LoyolaChicagoCode/unoapi-dpcpp-examples#6]
(without submitting to queue)

**Comment by gkthiruvathukal** [comment]
@klaeufer 
My inclination is to keep it. As I had indicated during our pairing today, I'm interested in looking at the performance of of sycl::buffer vs. vector. I expected performance to be comparable since both of these are likely _nicely tuned_, as I am known to say!
