### ISSUE TITLE
bring back delta times in ns using chronos

### ISSUE THREAD

**Issue by klaeufer** [LoyolaChicagoCode/unoapi-dpcpp-examples#9]

**Comment by gkthiruvathukal** [comment]
@klaeufer Thanks again for this.
Keep in mind that you are 100% correct that it doesn't matter most of the time. However, if I wanted to make a chart of size vs. execution time (to discuss scaling), this would be helpful. 

I'm completely on board with our in-person discussion about how we want to show the immense power of logging. Still, it wont' hurt for the log to show delta timings for each phase of the computation being performed (for all of our examples).

**Comment by gkthiruvathukal** [comment]
Consider having an output option, `--perfdata <device-name>` to write the data to a file with `<device-name>` to distinguish different devices where we want to measure performance. (Most of the time, we're interested in the GPU family.) To keep things as config free as possible, the output file can be named `perf-integration-<size>-<device-name>.json`.

There's almost no value to writing the performance results to the log. We really want them in seaprate output files.

```json
{ example : "integration", size : 100000, time : 50000, unit : "nanoseconds" }
```

I could then use `jq` to collate a bunch of files into CSV for processing with Pandas/Python.

**Comment by klaeufer** [comment]
TIME,DELTA,UNIT,DEVICE,PHASE
142238375696404,0,ns,sequential,Start
142238385102560,9406156,ns,sequential,Memory Allocation
142238432081377,46978817,ns,sequential,Integration
142240131637614,1699556237,ns,sequential,Output
142240131640698,3084,ns,sequential,DONE
142240131640698,1755944294,ns,sequential,TOTAL
